flags1_str={
    "M1_FLY":"M1_FLY",#+
"M1_SWIM":"M1_SWIM",#+
"M1_AMORPHOUS":"M1_AMORPHOUS",#+
"M1_WALLWALK":"M1_WALLWALK",#+
"M1_CLING":"M1_CLING",#+
"M1_TUNNEL":"M1_TUNNEL",#+
"M1_NEEDPICK":"M1_NEEDPICK",#+
"M1_CONCEAL":"M1_CONCEAL",#+
"M1_HIDE":"M1_HIDE",#+
"M1_AMPHIBIOUS":"M1_AMPHIBIOUS",#+
"M1_BREATHLESS":"M1_BREATHLESS",#+
"M1_NOTAKE":"M1_NOTAKE",
"M1_NOEYES":"M1_NOEYES",#+
"M1_NOHANDS":"M1_NOHANDS",#+
"M1_NOLIMBS":"M1_NOLIMBS",#+
"M1_NOHEAD":"M1_NOHEAD",#+
"M1_MINDLESS":"M1_MINDLESS",#+
"M1_HUMANOID":"M1_HUMANOID",#+
"M1_ANIMAL":"M1_ANIMAL",#+
"M1_SLITHY":"M1_SLITHY",#+
"M1_UNSOLID":"M1_UNSOLID",#+
"M1_THICK_HIDE":"M1_THICK_HIDE",#+
"M1_OVIPAROUS":"M1_OVIPAROUS",#+
"M1_REGEN":"M1_REGEN",#+
"M1_SEE_INVIS":"M1_SEE_INVIS",#+
"M1_TPORT":"M1_TPORT",#+
"M1_TPORT_CNTRL":"M1_TPORT_CNTRL",#+
"M1_ACID":"M1_ACID",#-
"M1_POIS":"M1_POIS",#-
"M1_CARNIVORE":"M1_CARNIVORE",#+
"M1_HERBIVORE":"M1_HERBIVORE",#+
"M1_OMNIVORE":"M1_OMNIVORE",#+
"M1_METALLIVORE":"M1_METALLIVORE",#+
"M1_MAGIVORE":"M1_MAGIVORE",#+

"M1_TENGTPORT":"M1_TENGTPORT",#+
"M1_FLOAT":"M1_FLOAT",#+
"M1_NOTONL":"M1_NOTONL",#+
"M1_FLEETFLEE":"M1_FLEETFLEE",#+
"M1_WEBRIP":"M1_WEBRIP",#+
"M1_DOORBUST":"M1_DOORBUST",#+
"M1_AQUATIC":"M1_AQUATIC",#+

"M1_CHILL":"M1_CHILL",#+
"M1_TOSTY":"M1_TOSTY",#+
"M1_HALUC":"M1_HALUC",#+

"M1_WINGS":"M1_WINGS",#+
"M1_LONGHEAD":"M1_LONGHEAD",#+
"M1_LONGNECK":"M1_LONGNECK",#+
"M1_NOFEET":"M1_NOFEET",#+
"M1_HAS_FEET":"M1_HAS_FEET",#+
"M1_CAN_AMULET":"M1_CAN_AMULET",#+
"M1_INDIGESTIBLE":"M1_INDIGESTIBLE",#not about eating, it is about englufing
"M1_INSUBSTANTIAL":"M1_INSUBSTANTIAL",#like shades
"M1_NOGLOVES":"M1_NOGLOVES",#+
"M1_NOHAT":"M1_NOHAT",#+
"M1_SKELETAL":"M1_SKELETAL",#+

"":""

}

flags2_str={
    "M2_NOPOLY":"M2_NOPOLY",#+
"M2_UNDEAD":"M2_UNDEAD",#+
"M2_WERE":"M2_WERE",#+
"M2_HUMAN":"M2_HUMAN",#+
"M2_ELF":"M2_ELF",#+
"M2_DWARF":"M2_DWARF",#+
"M2_GNOME":"M2_GNOME",#+
"M2_ORC":"M2_ORC",#+
"M2_VAMPIRE":"M2_VAMPIRE",
"M2_DEMON":"M2_DEMON",#+
"M2_MERC":"M2_MERC",#+
"M2_LORD":"M2_LORD",#+
"M2_PRINCE":"M2_PRINCE",#+
"M2_MINION":"M2_MINION",#+
"M2_GIANT":"M2_GIANT",#+
"M2_SHAPESHIFTER":"M2_SHAPESHIFTER",#+
"M2_MALE":"M2_MALE",#+
"M2_FEMALE":"M2_FEMALE",#+
"M2_NEUTER":"M2_NEUTER",#+
"M2_PNAME":"M2_PNAME",
"M2_HOSTILE":"M2_HOSTILE",#+
"M2_PEACEFUL":"M2_PEACEFUL",#+
"M2_DOMESTIC":"M2_DOMESTIC",#+
"M2_WANDER":"M2_WANDER",#+
"M2_STALK":"M2_STALK",#+
"M2_NASTY":"M2_NASTY",#+
"M2_STRONG":"M2_STRONG",
"M2_ROCKTHROW":"M2_ROCKTHROW",#+
"M2_GREEDY":"M2_GREEDY",#+
"M2_JEWELS":"M2_JEWELS",#+
"M2_COLLECT":"M2_COLLECT",#+
"M2_MAGIC":"M2_MAGIC",#+
"M2_HOBBIT":"M2_HOBBIT",#+
"M2_DRUID_FORM_A":"Druid Form A",#+
"M2_DRUID_FORM_B":"Druid Form B",#+
"M2_DRUID_FORM_C":"Druid Form C",#+
"M2_DRUID_FORM_D":"Druid Form D",#+


"":""
}

flags3_str={
    "M3_WANTSAMUL":"M3_WANTSAMUL",#+
"M3_WANTSBELL":"M3_WANTSBELL",#+
"M3_WANTSBOOK":"M3_WANTSBOOK",#+
"M3_WANTSCAND":"M3_WANTSCAND",#+
"M3_WANTSARTI":"M3_WANTSARTI",#+
"M3_WANTSALL":"M3_WANTSALL",#+
"M3_WAITFORU":"M3_WAITFORU",#+
"M3_CLOSE":"M3_CLOSE",#+
"M3_COVETOUS":"M3_COVETOUS",#+
"M3_WAITMASK":"M3_WAITMASK",
"M3_INFRAVISION":"M3_INFRAVISION",#+
"M3_INFRAVISIBLE":"M3_INFRAVISIBLE",#+
"M3_DISPLACES":"M3_DISPLACES",#+
"M3_GROUPATTACK":"M3_GROUPATTACK",#+
"M3_BLINKER":"M3_BLINKER",#+
"M3_NOREGEN":"M3_NOREGEN",#+
"M3_STATIONARY":"M3_STATIONARY",#+
"M3_ACCURATE":"M3_ACCURATE",#+
"M3_BERSERK":"M3_BERSERK",#+
"M3_SKITTISH":"M3_SKITTISH",#+
"M3_ULTRAVISION":"M3_ULTRAVISION",#+
"M3_TRAITOR":"M3_TRAITOR",#+
"M3_NOTAME":"M3_NOTAME",#+
"M3_NONCORPOREAL":"M3_NONCORPOREAL",#+

"M3_NORMAL":"M3_NORMAL",#+
"M3_DARKSIGHT":"M3_DARKSIGHT",#+
"M3_LOWLIGHT2":"M3_LOWLIGHT2",#+
"M3_LOWLIGHT3":"M3_LOWLIGHT3",#+
"M3_CATSIGHT":"M3_CATSIGHT",#+
"M3_ECHOLOCATE":"M3_ECHOLOCATE",#+
"M3_BLOODSENSE":"M3_BLOODSENSE",#+
"M3_LIFESENSE":"M3_LIFESENSE",#+
"M3_EXTRAMISSION":"M3_EXTRAMISSION",#+
"M3_TELEPATHIC":"M3_TELEPATHIC",#+
"M3_RLYEHIAN":"M3_RLYEHIAN",#+
"M3_DETECTION":"M3_DETECTION",#+
"M3_OMNI":"M3_OMNI",#+
"M3_SCENT":"M3_SCENT",#+
"M3_EARTHSENSE":"M3_EARTHSENSE",#+

"M3_OPAQUE":"M3_OPAQUE",#+
"M3_RIDER":"M3_RIDER",#+
"M3_DEADLY":"M3_DEADLY",#+
"M3_TRACKER":"M3_TRACKER",#+
"M3_NOSPELLCOOLDOWN":"M3_NOSPELLCOOLDOWN",#+

"M3_NOWISH":"M3_NOWISH",#+
"M3_BACKSTAB":"M3_BACKSTAB",#+
"M3_COMMANDER":"M3_COMMANDER",#+
"M3_SANLOSS":"M3_SANLOSS",#+
"M3_INSIGHT":"M3_INSIGHT",#+
"M3_RIDER_HP":"M3_RIDER_HP",#+
"M3_FUTURE_WISH":"M3_FUTURE_WISH",#+
"M3_BOLD":"M3_BOLD",#+
"M3_DETACHED":"M3_DETACHED",#+, not used currently?
"M3_DUMMY":"M3_DUMMY",#i don't know what is it
"":""

}

flags4_str={
    "M4_VULNERABLE_FIRE":"Hates fire",#+
"M4_VULNERABLE_COLD":"Hates cold",#+
"M4_VULNERABLE_ELEC":"Hates shock",#+
"M4_VULNERABLE_ACID":"Hates acid",#+
"M4_MARTIAL_B":"M4_MARTIAL_B",#+
"M4_MARTIAL_S":"M4_MARTIAL_S",#+
"M4_MARTIAL_E":"M4_MARTIAL_E",#+
"M4_BAB_FULL":"M4_BAB_FULL",#+
"M4_BAB_HALF":"M4_BAB_HALF",#+
"M4_LEVEL_30":"M4_LEVEL_30",#+
"M4_LEVEL_45":"M4_LEVEL_45",#+
"M4_PHYS_SCALING":"M4_PHYS_SCALING",#+
"M4_ELDER_SIGN":"M4_ELDER_SIGN",#-
"M4_EYE_OF_YGG":"M4_EYE_OF_YGG",#-
"M4_ELDER_EYE_ELEM":"M4_ELDER_EYE_ELEM",#-
"M4_ELDER_EYE_ENERGY":"M4_ELDER_EYE_ENERGY",#-
"M4_ELDER_EYE_PLANES":"M4_ELDER_EYE_PLANES",#-
"M4_HATESSILVER":"M4_HATESSILVER",#+
"M4_HATESIRON":"M4_HATESIRON",#+
"M4_HATESUNHOLY":"M4_HATESUNHOLY",#+
"M4_HATESHOLY":"M4_HATESHOLY",#+
"M4_RBLUNT":"M4_RBLUNT",#+
"M4_RSLASH":"M4_RSLASH",#+
"M4_RPIERCE":"M4_RPIERCE",#+
"M4_WRESIST":"M4_WRESIST",#+
"M4_HATESUNBLESSED":"M4_HATESUNBLESSED",#+
"":""
}
