at={'AT_CLAW':'Claw',
'AT_BITE':'Bite',
'AT_KICK':'Kick',
'AT_BUTT':'Butt',
'AT_TUCH':'Touch',
'AT_STNG':'Sting',
'AT_HUGS':'Hug',
'AT_SPIT':'Spit',
'AT_ENGL':'Engulf',
'AT_BREA':'Breath',
'AT_EXPL':'Explode',
'AT_BOOM':'Explode',
'AT_GAZE':'Gaze',
'AT_TENT':'Suck',
'AT_SCRE':'Scream',
'AT_WEAP':'Weapon',
'AT_MAGC':'Spell',
'AT_NONE':"Passive",
"AT_MULTIPLY":"Multiply",
"AT_ARRW":"Shoot",
"AT_WHIP":"Whip",
"AT_LRCH":"2-Reach",
"AT_HODS":"Mirror",
"AT_LNCK":"2-Reach Bite",
"AT_MMGC":"Spell",
"AT_ILUR":"Swallow",
"AT_HITS":"Autohit",
"AT_WISP":"Mist",
"AT_TNKR":"Tinker",
"AT_SRPR":"Spiritual rapier",
"AT_BEAM":"Beam",
"AT_DEVA":"Million arm",
"AT_5SQR":"5-Reach Touch",
"AT_5SBT":"5-Reach Bite",
"AT_WDGZ":"Wide gaze",
"AT_REND":"Combo",
"AT_VINE":"Vines",
"AT_BKGT":"Goat Random",
"AT_BKG2":"Goat Random",
"AT_XSPR":"Spiritual rapier offhand",
"AT_MSPR":"Spiritual rapier extra hand",
"AT_DSPR":"Spiritual rapier million-arm",
"AT_ESPR":"Spiritual rapier floating",
"AT_OBIT":"Unusual Bite",
"AT_WBIT":"Wolf Head Bite",
"AT_TAIL":"Tail",
"AT_TONG":"Tongue",
"AT_VOMT":"Vomit",
"AT_XWEP":"Offhand Weapon",
"AT_MARI":"Extra Weapon",
"AT_BRSH":"Splash",
}

at_short={'AT_CLAW':'Claw',
'AT_BITE':'Bite',
'AT_KICK':'Kick',
'AT_BUTT':'Butt',
'AT_TUCH':'Tch',
'AT_STNG':'Stng',
'AT_HUGS':'Hug',
'AT_SPIT':'Spit',
'AT_ENGL':'Englf',
'AT_BREA':'Brth',
'AT_EXPL':'Xplode',
'AT_BOOM':'Xplode',
'AT_GAZE':'Gz',
'AT_TENT':'Suck',
'AT_SCRE':'Scream',
'AT_WEAP':'Weap',
'AT_MAGC':'Spell',
'AT_NONE':"Pasv",
"AT_MULTIPLY":"Multiply",
"AT_ARRW":"Shoot",
"AT_WHIP":"Whip",
"AT_LRCH":"2-Reach",
"AT_HODS":"Mirror",
"AT_LNCK":"2-Reach Bite",
"AT_MMGC":"Spell",
"AT_ILUR":"Swallow",
"AT_HITS":"Autohit",
"AT_WISP":"Mist",
"AT_TNKR":"Tinker",
"AT_SRPR":"Spirit.",
"AT_BEAM":"Beam",
"AT_DEVA":"Million arm",
"AT_5SQR":"5-sq Touch",
"AT_5SBT":"5-sq Bite",
"AT_WDGZ":"Wide gz",
"AT_REND":"Combo",
"AT_VINE":"Vines",
"AT_BKGT":"Goat Rand",
"AT_BKG2":"Goat Rand",
"AT_XSPR":"Spirit. offh",
"AT_MSPR":"Spirit. Xtra hand",
"AT_DSPR":"Spirit. million-arm",
"AT_ESPR":"Spirit. floating",
"AT_OBIT":"Unusual Bite",
"AT_WBIT":"Wolf Head Bite",
"AT_TAIL":"Tail",
"AT_TONG":"Tongue",
"AT_VOMT":"Vomit",
"AT_XWEP":"Offh Weap",
"AT_MARI":"Xtra Weap",
"AT_BRSH":"Splash",
}
ad={'AD_PHYS':'',
'AD_MAGM':' M. Missile',
'AD_FIRE':' Fire',
'AD_COLD':' Cold',
'AD_SLEE':' Sleep',
'AD_DISN':' Disint.',
'AD_ELEC':' Shock',
'AD_DRST':' Poison -St',
'AD_ACID':' Acid',
'AD_SPC1':' SPC1',
'AD_SPC2':' Stun',
'AD_BLND':' Blind',
'AD_STUN':' Stun',
'AD_SLOW':' Slow',
'AD_PLYS':' Paralyze',
'AD_DRLI':' Drain life',
'AD_DREN':' Drain Pw',
'AD_LEGS':' Legs',
'AD_STON':' Petrify',
'AD_STCK':' Sticky',
'AD_SGLD':' Steal gold',
'AD_SITM':' Steal',
'AD_SEDU':' Steal',#now works similar
'AD_TLPT':' Teleport',
'AD_RUST':' Rust',
'AD_CONF':' Conf',
'AD_DGST':' Digest',
'AD_HEAL':' Heal',
'AD_WRAP':' Drowning',
'AD_WERE':' Lycantropy',
'AD_DRDX':' Poison -Dx',
'AD_DRCO':' Poison -Co',
'AD_DRIN':' -In',
'AD_DISE':' Disease',
'AD_DCAY':' Decay organics',
'AD_SSEX':' Seduce',
'AD_HALU':' Hallu',
'AD_DETH':' Deadly touch',
'AD_PEST':' Plus disease',
'AD_FAMN':' Plus hunger',
'AD_SLIM':' Slime',
'AD_ENCH':' Disenchant',
'AD_CORR':' Corrode',
'AD_CLRC':' Clerical',
'AD_SPEL':' Mage',
'AD_RBRE':' Random',
'AD_SAMU':' -Artifact',
'AD_CURS':' -Intrinsic',
'AD_CNCL':' Cancel',
'AD_POLY':' Polymorph',
"AD_PITS":' Pits',
"AD_WTHR":' Wither',
"AD_LAVA":' Lava',
"AD_LUCK":' -Luck',
"AD_FREZ":' Freeze',
"AD_HEAD":' Decapitate',
"AD_BHED":' Decapitate',
"AD_PUNI":' Punish',
"AD_LVLT":' Levelport',
"AD_BLNK":' Mental invasion',
"AD_SPOR":' Spore',
"AD_PSYC":' Psy',
"AD_WEBS":' Web',
"AD_FUSE":' Fused damage',
"AD_LOUD":' Sound',
"AD_CLOB":' Knock-back',
"AD_CALM":' Calm',
"AD_TCKL":' Tickle',

"AD_POSN":" Poison",
"AD_WISD":" -Wi",
"AD_VORP":" Vorpal",
"AD_SHRD":" Shred armor",
"AD_SLVR":" Silver arrow",
"AD_BALL":" Iron ball",
"AD_BLDR":" Boulder",
"AD_VBLD":" Boulder volley",
"AD_WET":" Water",
"AD_LETHE":" Lethe water",
"AD_BIST":" Bisecting beak",
"AD_DEAD":" Deadly",
"AD_SUCK":" Suck",
"AD_MALK":" Paralyze&destroy wands",
"AD_UVUU":" Brainspike",
"AD_ABDC":" Abduction",
"AD_KAOS":" Spawn Chaos",
"AD_LSEX":" Plus seduce",
"AD_HLBD":" Call demons",
"AD_SPNL":" Spawn Leviathan/Levistus",
"AD_MIST":" Mist",
"AD_TELE":" Self-teleport",
"AD_PSON":" Psyonic",
"AD_GROW":" Boost autons on death",
"AD_SOUL":" Boost Deep Ones on death",
"AD_TENT":" Plus tentacles",
"AD_JAILER":" Spawn Lucifer",
"AD_AXUS":" Fire-Shock-Drain-Cold combo",
"AD_UNKNWN":" Unknown",
"AD_SOLR":" Silver arrow",
"AD_CHKH":" Grow with number of Chokhmah",
"AD_HODS":" Your weapon",
"AD_CHRN":" Cursed horn",
"AD_LOAD":" Loadstone",
"AD_GARO":" Rumor",
"AD_GARO_MASTER":" Major consultation",
"AD_WEEP":" Levelport+drain",
"AD_FNEX":" Fern",
"AD_SSUN":" Blind+fire",
"AD_MAND":" Deadly shriek",
"AD_BARB":" Retalitate",
"AD_VAMP":" Drain blood",
"AD_ILUR":" Amnesia+rust",
"AD_TNKR":" Spawn gizmo",
"AD_FRWK":" Explode several",
"AD_STDY":" Study",
"AD_OONA":" Fire/Cold/Shock",
"AD_NTZC":" Anti-equipment",
"AD_WTCH":" Spawn tentacles",
"AD_SHDW":" Shadow (poison)",
"AD_STTP":" Teleport armor",
"AD_HDRG":" Random at creation",
"AD_STAR":" Silver",
"AD_EELC":" Elem. Shock",
"AD_EFIR":" Elem. Fire",
"AD_EDRC":" Elem. Poison -Co",
"AD_ECLD":" Elem. Cold",
"AD_EACD":" Elem. Acid",
"AD_CNFT":" Plus Conflict",
"AD_BLUD":" Blood",
"AD_SURY":" +50 Silver",
"AD_NPDC":" -Co",
"AD_GLSS":" Silver shards",#silver
"AD_MERC":" Mercury cold+abuse",
"AD_GOLD":" Goldify",
"AD_ACFR":" Holy fire",
"AD_DESC":" Suck water",
"AD_BLAS":" Anger god",
"AD_SESN":" Four seasons (cold/shred/pollen/-Life)",
"AD_POLN":" Pollen paralyze",
"AD_BDFN":" Bloody spears",
"AD_SPHR":" Spawn spheres",
"AD_DARK":" Dark",
"AD_LRVA":" Implant larva+poison -Co",
"AD_NPDS":" -St",
"AD_NPDD":" -Dx",
"AD_NPDR":" -Ch",
"AD_NPDA":" -all stats",
"AD_HOOK":" Flesh hook immobilize",
"AD_MDWP":" Mindwipe drain+amnesia",
"AD_SSTN":" Petrify",
"AD_DOBT":" Doubt",
"AD_APCS":" Revelatory whispers",
"AD_PULL":" Pull closer",
"AD_PAIN":" Pain scream+Poison -St",
"AD_MROT":" Mummy curse",
"AD_PYCL":" Fire/poison/phys/blind",
"AD_MOON":" Silver (moon phase dependent)",#silver
"AD_HOLY":" Holy",
"AD_UNHY":" Unholy",
"AD_PERH":" Mul. by monster level",
"AD_SVPN":" Severe posion",
"AD_HLUH":" Holy+Unholy",
"AD_TSMI":" Steal magic items",
"AD_BYAK":" Implant egg to armor",
"AD_BSTR":" Unholy+curse",
"AD_UNRV":" Unnerving",
"AD_MADF":" Madness fire",#player only?
"AD_FATK":" Force to attack",#player only?
"AD_DRHP":" Drain bonus HP",
"AD_PUSH":" Push",
"AD_LICK":" Pull&Immobilize&Cold+Acid",
"AD_PFBT":" Rot+Poison",
"AD_OMUD":" Acid+bone daggers",
"AD_DUNSTAN":" Stones throw themselves at target",#player only?
"AD_IRIS":" Iridescent tentacles",#player only?
"AD_NABERIUS":" Tarnished bloody fangs",#player only?
"AD_OTIAX":" Mist tendrils",#player only?
"AD_SIMURGH":" Thirty-colored feathers",#player only?
"AD_CMSL":" Cold missile",
"AD_FMSL":" Fire missile",
"AD_EMSL":" Shock missile",
"AD_SMSL":" Physical missile",
"AD_WMTG":" War Machine targeting gaze",
"AD_SQUE":" Steal Quest Artifact or Amulet",
"AD_RGAZ":" Random",
"AD_RETR":" Random (fire/cold/shock)",
}
ad_short={'AD_PHYS':'',
'AD_MAGM':' M. Missile',
'AD_FIRE':' Fire',
'AD_COLD':' Cold',
'AD_SLEE':' Sleep',
'AD_DISN':' Disint.',
'AD_ELEC':' Shock',
'AD_DRST':' Poison -St',
'AD_ACID':' Acid',
'AD_SPC1':' SPC1',
'AD_SPC2':' Stun',
'AD_BLND':' Blind',
'AD_STUN':' Stun',
'AD_SLOW':' Slow',
'AD_PLYS':' Prlz',
'AD_DRLI':' -Lv',
'AD_DREN':' -Pw',
'AD_LEGS':' Legs',
'AD_STON':' Petrify',
'AD_STCK':' Sticky',
'AD_SGLD':' Steal gold',
'AD_SITM':' Steal',
'AD_SEDU':' Steal',#now works similar
'AD_TLPT':' Tele',
'AD_RUST':' Rust',
'AD_CONF':' Conf',
'AD_DGST':' Digest',
'AD_HEAL':' Heal',
'AD_WRAP':' Drown',
'AD_WERE':' Lycantropy',
'AD_DRDX':' Poison -Dx',
'AD_DRCO':' Poison -Co',
'AD_DRIN':' -In',
'AD_DISE':' Disease',
'AD_DCAY':' Decay organics',
'AD_SSEX':' Seduce',
'AD_HALU':' Hallu',
'AD_DETH':' Deadly',
'AD_PEST':' Plus disease',
'AD_FAMN':' Plus hunger',
'AD_SLIM':' Slime',
'AD_ENCH':' Disenchant',
'AD_CORR':' Corrode',
'AD_CLRC':' Cler',
'AD_SPEL':' Mage',
'AD_RBRE':' Rand',
'AD_SAMU':' -Arti',
'AD_CURS':' -Intrinsic',
'AD_CNCL':' Cancel',
'AD_POLY':' Polymorph',
"AD_PITS":' Pits',
"AD_WTHR":' Wither',
"AD_LAVA":' Lava',
"AD_LUCK":' -Luck',
"AD_FREZ":' Freeze',
"AD_HEAD":' Decapitate',
"AD_BHED":' Decapitate',
"AD_PUNI":' Punish',
"AD_LVLT":' Levelport',
"AD_BLNK":' Mental invasion',
"AD_SPOR":' Spore',
"AD_PSYC":' Psy',
"AD_WEBS":' Web',
"AD_FUSE":' Fused damage',
"AD_LOUD":' Sound',
"AD_CLOB":' Knock-back',
"AD_CALM":' Calm',
"AD_TCKL":' Tickle',

"AD_POSN":" Poison",
"AD_WISD":" -Wi",
"AD_VORP":" Vorpal",
"AD_SHRD":" Shred armor",
"AD_SLVR":" Silver arrow",
"AD_BALL":" Iron ball",
"AD_BLDR":" Boulder",
"AD_VBLD":" Boulder volley",
"AD_WET":" Water",
"AD_LETHE":" Lethe water",
"AD_BIST":" Bisect",
"AD_DEAD":" Deadly",
"AD_SUCK":" Suck",
"AD_MALK":" Paralyze&destroy wands",
"AD_UVUU":" Brainspike",
"AD_ABDC":" Abduct",
"AD_KAOS":" Spawn Chaos",
"AD_LSEX":" Plus seduce",
"AD_HLBD":" Call demons",
"AD_SPNL":" Spawn Leviathan/Levistus",
"AD_MIST":" Mist",
"AD_TELE":" Self-teleport",
"AD_PSON":" Psyonic",
"AD_GROW":" Boost autons",
"AD_SOUL":" Boost Deep Ones",
"AD_TENT":" Plus tentacles",
"AD_JAILER":" Spawn Lucifer",
"AD_AXUS":" Fire-Shock-Drain-Cold combo",
"AD_UNKNWN":" Unknown",
"AD_SOLR":" Silver arrow",
"AD_CHKH":" Grow with number of Chokhmah",
"AD_HODS":" Your weapon",
"AD_CHRN":" Cursed horn",
"AD_LOAD":" Loadstone",
"AD_GARO":" Rumor",
"AD_GARO_MASTER":" Major consultation",
"AD_WEEP":" Levelport+drain",
"AD_FNEX":" Fern",
"AD_SSUN":" Blind+fire",
"AD_MAND":" Deadly shriek",
"AD_BARB":" Retalitate",
"AD_VAMP":" Drain blood",
"AD_ILUR":" Amnesia+rust",
"AD_TNKR":" Spawn gizmo",
"AD_FRWK":" Explode several",
"AD_STDY":" Study",
"AD_OONA":" Fire/Cold/Shock",
"AD_NTZC":" Anti-equipment",
"AD_WTCH":" Spawn tentacles",
"AD_SHDW":" Shadow",
"AD_STTP":" Teleport armor",
"AD_HDRG":" Rand at creation",
"AD_STAR":" Silver",
"AD_EELC":" Elem. Shock",
"AD_EFIR":" Elem. Fire",
"AD_EDRC":" Elem. Poison -Co",
"AD_ECLD":" Elem. Cold",
"AD_EACD":" Elem. Acid",
"AD_CNFT":" Plus Conflict",
"AD_BLUD":" Blood",
"AD_SURY":" +50 Silver",
"AD_NPDC":" -Co",
"AD_GLSS":" Silver shards",#silver
"AD_MERC":" Mercury",
"AD_GOLD":" Goldify",
"AD_ACFR":" Holy fire",
"AD_DESC":" Suck water",
"AD_BLAS":" Anger god",
"AD_SESN":" Four seasons",
"AD_POLN":" Pollen paralyze",
"AD_BDFN":" Bloody spears",
"AD_SPHR":" Spawn spheres",
"AD_DARK":" Dark",
"AD_LRVA":" Implant larva",
"AD_NPDS":" -St",
"AD_NPDD":" -Dx",
"AD_NPDR":" -Ch",
"AD_NPDA":" -all stats",
"AD_HOOK":" Flesh hook",
"AD_MDWP":" Mindwipe",
"AD_SSTN":" Petrify",
"AD_DOBT":" Doubt",
"AD_APCS":" Revelatory whispers",
"AD_PULL":" Pull",
"AD_PAIN":" Pain scream",
"AD_MROT":" Mummy curse",
"AD_PYCL":" Fire/poison/phys/blind",
"AD_MOON":" Silver Moon",#silver
"AD_HOLY":" Holy",
"AD_UNHY":" Unholy",
"AD_PERH":" Mul. by monster level",
"AD_SVPN":" Severe posion",
"AD_HLUH":" Holy+Unholy",
"AD_TSMI":" Steal magic items",
"AD_BYAK":" Implant egg to armor",
"AD_BSTR":" Unholy+curse",
"AD_UNRV":" Unnerving",
"AD_MADF":" Madness fire",#player only?
"AD_FATK":" Force to attack",#player only?
"AD_DRHP":" Drain bonus HP",
"AD_PUSH":" Push",
"AD_LICK":" Pull&Immobilize&Cold+Acid",
"AD_PFBT":" Rot+Poison",
"AD_OMUD":" Acid+bone daggers",
"AD_DUNSTAN":" Stones throw themselves at target",#player only?
"AD_IRIS":" Iridescent tentacles",#player only?
"AD_NABERIUS":" Tarnished bloody fangs",#player only?
"AD_OTIAX":" Mist tendrils",#player only?
"AD_SIMURGH":" Thirty-colored feathers",#player only?
"AD_CMSL":" Cold missile",
"AD_FMSL":" Fire missile",
"AD_EMSL":" Shock missile",
"AD_SMSL":" Physical missile",
"AD_WMTG":" War Machine targeting gaze",
"AD_SQUE":" Steal Quest Artifact or Amulet",
"AD_RGAZ":" Rand",
"AD_RETR":" Rand (fire/cold/shock)",
}
